PATIENT_FEATURES = [
    "AGE",
    "GENDER",
    "HGT_CM_CALC",
    "WGT_KG_CALC",
    "abo",
    "BMI_CALC",
    "CREAT_TX",
    "INR_TX",
    "TBILI_TX",
    "MELD_PELD_LAB_SCORE",
    "FINAL_SERUM_SODIUM",
    "DIAL_TX",
    "meldstat",
    "status1",
    "ALBUMIN_TX",
    "ASCITES_TX",
    "ETHCAT",
    "EXC_HCC",
    "FUNC_STAT_TRR",
    #'HCV_SEROSTATUS',
    "LIFE_SUP_TRR",
    "ON_VENT_TRR",
    #'MED_COND_TRR',
    "PORTAL_VEIN_TRR",
    "PREV_AB_SURG_TRR",
    "NUM_PREV_TX",
    #'PREV_TX',
    "diag1",
    "statushcc",
    #'HBV_CORE',
]

ORGAN_FEATURES = [
    "AGE_DON",
    "GENDER_DON",
    "HGT_CM_DON_CALC",
    "WGT_KG_DON_CALC",
    "TBILI_DON",
    "abodon",
    "COD_CAD_DON",
    #'COLD_ISCH',# (cold ischemia time which is the length of time from the donor being recovered until it is transplanted)
    "CREAT_DON",
    "ETHCAT_DON",
    "NON_HRT_DON",
    "SHARE_TY",
    "death_mech_don_group",
    "deathcirc",
    "TXLIV",
    "HEP_C_ANTI_DON",
    "HBV_CORE_DON",
    "SGOT_DON",
    "SGPT_DON",
    "macro",
    "micro",
]

INITIAL_PATIENT_FEATURES = [
    "INIT_AGE",
    "HGT_CM_TCR",
    "INIT_WGT_KG",
    "INIT_BMI_CALC",
    "INIT_ALBUMIN",
    "INIT_ASCITES",
    "INIT_SERUM_CREAT",
    "INIT_DIALYSIS_PRIOR_WEEK",
    "INIT_INR",
    "INIT_MELD_PELD_LAB_SCORE",
    "INIT_SERUM_SODIUM",
    "FUNC_STAT_TCR",
    "LIFE_SUP_TCR",
    "PORTAL_VEIN_TCR",
    "PREV_AB_SURG_TCR",
]

COLUMN_IS_CATEGORICAL = {
    "AGE": False,
    "GENDER": True,
    "HGT_CM_CALC": False,
    "WGT_KG_CALC": False,
    "abo": True,
    "BMI_CALC": False,
    "CREAT_TX": False,
    "INR_TX": False,
    "TBILI_TX": False,
    "MELD_PELD_LAB_SCORE": False,
    "FINAL_SERUM_SODIUM": False,
    "DIAL_TX": True,
    "meldstat": True,
    "status1": True,
    "ALBUMIN_TX": False,
    "ASCITES_TX": True,
    "ETHCAT": True,
    "EXC_HCC": True,
    "FUNC_STAT_TRR": True,
    "HCV_SEROSTATUS": True,
    "LIFE_SUP_TRR": True,
    "ON_VENT_TRR": True,
    "MED_COND_TRR": True,
    "PORTAL_VEIN_TRR": True,
    "PREV_AB_SURG_TRR": True,
    "NUM_PREV_TX": False,
    "PREV_TX": True,
    "diag1": True,
    "statushcc": True,
    "HBV_CORE": True,
    "AGE_DON": False,
    "GENDER_DON": True,
    "HGT_CM_DON_CALC": False,
    "WGT_KG_DON_CALC": False,
    "TBILI_DON": False,
    "abodon": True,
    "COD_CAD_DON": True,
    "COLD_ISCH": False,
    "CREAT_DON": False,
    "ETHCAT_DON": True,
    "NON_HRT_DON": True,
    "SHARE_TY": True,
    "death_mech_don_group": True,
    "deathcirc": True,
    "TXLIV": True,
    "HEP_C_ANTI_DON": True,
    "HBV_CORE_DON": True,
    "SGOT_DON": False,
    "SGPT_DON": False,
    "macro": True,
    "micro": True,
    "INIT_AGE": False,
    "HGT_CM_TCR": False,
    "INIT_WGT_KG": False,
    "INIT_BMI_CALC": False,
    "INIT_ALBUMIN": False,
    "INIT_ASCITES": True,
    "INIT_SERUM_CREAT": False,
    "INIT_DIALYSIS_PRIOR_WEEK": True,
    "INIT_INR": False,
    "INIT_MELD_PELD_LAB_SCORE": False,
    "INIT_SERUM_SODIUM": False,
    "FUNC_STAT_TCR": True,
    "LIFE_SUP_TCR": True,
    "PORTAL_VEIN_TCR": True,
    "PREV_AB_SURG_TCR": True,
    "PTIME": False,
    "PSTATUS": True,
    "REGION": True,
    "DONOR_ID": False,
    "WL_ID_CODE": False,
    "LISTING_CTR_CODE": False,
}

substitution_pairs = [
    ("AGE", "INIT_AGE"),
    ("ALBUMIN_TX", "INIT_ALBUMIN"),
    ("ASCITES_TX", "INIT_ASCITES"),
    ("BMI_CALC", "INIT_BMI_CALC"),
    ("CREAT_TX", "INIT_SERUM_CREAT"),
    #    ('DIAL_TX','INIT_DIALYSIS_PRIOR_WEEK'),
    ("FINAL_SERUM_SODIUM", "INIT_SERUM_SODIUM"),
    ("FUNC_STAT_TRR", "FUNC_STAT_TCR"),
    ("HGT_CM_CALC", "HGT_CM_TCR"),
    ("INR_TX", "INIT_INR"),
    ("LIFE_SUP_TRR", "LIFE_SUP_TCR"),
    ("MELD_PELD_LAB_SCORE", "INIT_MELD_PELD_LAB_SCORE"),
    ("PORTAL_VEIN_TRR", "PORTAL_VEIN_TCR"),
    ("PREV_AB_SURG_TRR", "PREV_AB_SURG_TCR"),
    ("WGT_KG_CALC", "INIT_WGT_KG"),
    ("ON_VENT_TRR", "VENTILATOR_TCR"),
]
